#!/bin/bash

alias ls='ls -Fh --color=auto'
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ll -a'
alias duh='du -h'
alias dfh='df -h'

#alias rdesktop='rdesktop -g 1280x1024'
#alias mstsc='rdesktop'

alias nobyobu='export LC_BYOBU=0'

alias rehash='hash -r'
#alias free='free -mt'
alias idle='nice -n19 ionice -c3'

alias zls='zfs list -o name,used,avail,refer,mountpoint,usedbysnapshots,compress,compressratio,usedbychildren,usedbydataset,usedbyrefreservation,usedbysnapshots'
alias zfsls='zls'
