# This is sourced always, even when zshrc is not (ie from macvim)

# Dedupe entries
typeset -Ug path

# Make sure gnubin is before usr/local. For most things, that is. OSX is hilarious.
path=("/usr/local/libexec/gnubin" "/usr/local/opt/ccache/libexec" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "/bin" "/sbin" $path[@])
path=("$HOME/.bin" "$HOME/.local/bin" "$HOME/.pyenv/shims" "$HOME/.rbenv/shims" "$HOME/go/bin" $path[@])

# Man
typeset -Ug manpath
manpath=("$HOME/.local/share/man" "/usr/local/share/man" "/usr/share/man" $manpath[@])

