# This is sourced always, even when zshrc is not (ie from macvim)

# Dedupe entries
typeset -Ug path

# Make sure gnubin is before usr/local
path=(/usr/local/libexec/gnubin /usr/local/opt/ccache/libexec /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /bin /sbin $path[@])
# pyenv
#path=(~/.pyenv/shims ~/.pyenv/bin $path[@])
# go
#path=(~/go/bin $path[@])
# wrapper bin
#path=(~/.local/bin ~/.bin $path[@])

path=(~/.bin ~/.local/bin ~/.pyenv/shims ~/.rbenv/shims ~/go/bin $path[@])

typeset -Ug manpath
manpath=("/usr/local/share/man" "/usr/share/man" $manpath[@])

