#!/bin/bash

# load defaults
#[ -f "/etc/bash.bashrc" ] && . /etc/bash.bashrc

# Don't load anything else if we're not interactive
#shopt -oq posix && return

# Set path accordingly
# $HOME/.cross/bin $HOME/code/android-sdk-linux/tools $HOME/.cabal/bin $HOME/bin $HOME/.bin /usr/lib/ccache
for p in "$HOME/.bin" "$HOME/.cabal/bin"; do
        [ -d "$p" ] && export PATH="$p:$PATH"
done
#export CCACHE_NLEVELS=5

# Set DISPLAY if it's empty
[ -z "$DISPLAY" ] && export DISPLAY=:0.0

# check for running jobs before allowing exit
shopt -s checkjobs

alias ls='ls -Fh --color=auto'
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ll -a'
alias duh='du -h'
alias dfh='df -h'

#alias rdesktop='rdesktop -g 1280x1024'
#alias mstsc='rdesktop'

# Mac only
#alias mysql=/usr/local/mysql/bin/mysql
#alias mysqladmin=/usr/local/mysql/bin/mysqladmin


