#!/bin/bash

# Set path accordingly
# $HOME/.cross/bin $HOME/code/android-sdk-linux/tools $HOME/.cabal/bin $HOME/bin $HOME/.bin /usr/lib/ccache
for p in "$HOME/.bin" "$HOME/.cabal/bin" "$HOME/.local/google_appengine"; do
        [ -d "$p" ] && export PATH="$p:$PATH"
done
