#!/bin/bash

alias solarsanweb='pushd ~/Projects/solarsanweb; . ./bin/env'
#alias solarsan='pushd ~/Projects/solarsan; workon solarsan'
alias san='solarsanweb'

alias emagnifigance='pushd ~/Projects/emagnifigance; . ./bin/env'

alias locsol_stor0='ssh root@10.14.38.20'
alias locsol_stor1='ssh root@10.14.38.11'
alias locsol_stor2='ssh root@10.14.38.12'
alias locsol_stor3='ssh root@10.16.38.13'
alias locsol_stor4='ssh root@10.16.38.14'

alias rehash='hash -r'
#alias free='free -mt'
alias idle='nice -n19 ionice -c3'

alias zls='zfs list -o name,used,avail,refer,mountpoint,usedbysnapshots,compress,compressratio,usedbychildren,usedbydataset,usedbyrefreservation,usedbysnapshots'
alias zfsls='zls'

#function cd() {
#    case "$*" in
#        -)      builtin cd "$@" ;;
#        ..)     popd ;;
#        *)      builtin pushd "$@" ;;
#    esac
#}

man () {
  case "$(type -t "$1"):$1" in
    builtin:*) help "$1" | "${PAGER:-less}";;     # built-in
    *[[?*]*) help "$1" | "${PAGER:-less}";;       # pattern
    *) command -p man "$@";;  # something else, presumed to be an external command
                              # or options for the man command or a section number
  esac
}

