#!/bin/bash

: ${GOPATH:="~/go"}
#: ${GOBIN:="$GOROOT/bin"}
#: ${GOARCH:="$(uname -m)"}
#: ${GOOS:="${SYSTEM:-$(uname -s)}"}
#export GOROOT GOBIN GOARCH GOOS

#: ${GOENV_ROOT:="~/.goenv"}

export \
    GOPATH \
    GO15VENDOREXPERIMENT=1 \
    PATH="$PATH:$GOPATH/bin" \
    && :

