#!/bin/sh

: ${PYENV_ROOT:="$HOME/.pyenv"}
export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

## pyenv
alias pv='pyenv'
alias activate='pyenv activate'
#alias deactivate='pyenv deactivate'
if has_cmd pyenv; then
    #eval "$(pyenv init - --no-rehash "$CURRENT_SHELL")"
    eval "$(pyenv init - "$CURRENT_SHELL")"

    # If we don't do the above then this is needed
    #source "$PYENV_ROOT/completions/pyenv."$CURRENT_SHELL""

    ## virtualenv
    #export PYENV_VIRTUALENV_CACHE_PATH="$CACHES_DIR/pip"
    # Used to check if this bin existed, but can't do that without each plugin being in PATH, ugh
    eval "$(pyenv virtualenv-init - "$CURRENT_SHELL")" || :

    ## virtualenvwrapper
    #export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
    pyenv virtualenvwrapper || :
fi

