#!/bin/bash
#bash_theme git-prompt
#bash_theme b-con

# Grr
#export POWERLINE_DEFAULT_MODE="$"
#export POWERLINE_MODE="$"

#. ~/.vim/repos/powerline/powerline/bindings/bash/powerline.sh
. ~/.bash/themes/airline.sh

