#!/bin/bash

## Don't load anything else if we're not interactive
shopt -oq posix && return

## ~/.bash rc.d and completion.d and "-local"s
for i in "$HOME/.bash/"{rc,completion}".d/"* "$HOME/.bash/"{rc,completion}".d-local/"*; do
    [[ -x "$i" || -h "$i" ]] && . "$i"
done

# EOF
