#!/bin/zsh

##
## modules
##
zmodload zsh/attr zsh/clone zsh/compctl zsh/computil zsh/datetime \
    zsh/mathfunc zsh/pcre zsh/regex zsh/param/private \
    zsh/sched zsh/system \
    zsh/termcap zsh/terminfo zsh/zpty zsh/zselect zsh/zutil
#zmodload zsh/files

##
## Opts
##

# globs
setopt \
    nullglob extended_glob case_glob \
    autocd cdablevars autolist autopushd \
    nomenucomplete listpacked listtypes bashautolist listambiguous \
    markdirs checkjobs \
    && :

autoload -Uz \
    zrecompile \
    relative \
    zargs \
    zcalc \
    zstyle+ \
    ztodo \
    bashcompinit \
    sticky-note \
    zkbd \
    incremental-complete-word \
    zsh-mime-setup zsh-mime-handler \
    pick-web-browser \
    nslookup \
    regexp-replace \
    chpwd_recent_dirs cdr add-zsh-hook \
    promptinit \
    && :

promptinit

add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':completion:*:*:cdr:*:*' menu selection

bindkey '^Xi' incremental-complete-word

zle -N predict-on
zle -N predict-off
bindkey '^X^Z' predict-on
bindkey '^Z' predict-off

zsh-mime-setup
alias -s html=pick-web-browser

