#!/bin/bash

alias rehash='hash -r'
#alias free='free -mt'
alias idle='nice -n19 ionice -c3'

alias zls='zfs list -o name,used,avail,refer,mountpoint,usedbysnapshots,compress,compressratio,usedbychildren,usedbydataset,usedbyrefreservation,usedbysnapshots'
alias zfsls='zls'

#function cd() {
#    case "$*" in
#        -)      builtin cd "$@" ;;
#        ..)     popd ;;
#        *)      builtin pushd "$@" ;;
#    esac
#}

man () {
  case "$(type -t "$1"):$1" in
    builtin:*) help "$1" | "${PAGER:-less}";;     # built-in
    *[[?*]*) help "$1" | "${PAGER:-less}";;       # pattern
    *) command -p man "$@";;  # something else, presumed to be an external command
                              # or options for the man command or a section number
  esac
}

# Include local aliases if possible
[[ ! -f "$HOME/.bash/aliases-local" ]] || . "$HOME/.bash/aliases-local"
