#!/bin/bash

alias rehash='hash -r'
#alias free='free -mt'
alias idle='nice -n19 ionice -c3'

alias zls='zfs list -o name,used,avail,refer,mountpoint,usedbysnapshots,compress,compressratio,usedbychildren,usedbydataset,usedbyrefreservation,usedbysnapshots'
alias zfsls='zls'

#function cd() {
#    case "$*" in
#        -)      builtin cd "$@" ;;
#        ..)     popd ;;
#        *)      builtin pushd "$@" ;;
#    esac
#}
