#!/bin/bash
alias ls='ls -Fh --color=auto'
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ll -a'
alias duh='du -h'
alias dfh='df -h'

#alias rdesktop='rdesktop -g 1280x1024'
#alias mstsc='rdesktop'

# Mac only
#alias mysql=/usr/local/mysql/bin/mysql
#alias mysqladmin=/usr/local/mysql/bin/mysqladmin

alias nobyobu='export LC_BYOBU=0'

